grpc:
  portDefault: 3001

pub:
  projectID: learn-drive-253814

sub:
  projectID: learn-drive-253814

repo:
  mongoConnectString: mongodb+srv://admin:110289@bookingcluster-tgpah.gcp.mongodb.net/test?retryWrites=true&w=majority
  mongoDBName: teacher

micro:
  learnerHostDefault: ""
  learnerPortDefault: 3002
  bookingHostDefault: ""
  bookingPortDefault: 3003

jwt:
  secretKey: mySuperSecretKeyLol
  tokenExpired: 72 #hour
  issuer: micro_teacher #hour