grpc:
  portDefault: 5001


micro:
  teacherHostDefault: ""
  teacherPortDefault: 3001
  learnerHostDefault: ""
  learnerPortDefault: 3002
  bookingHostDefault: ""
  bookingPortDefault: 3003
  paymentHostDefault: ""
  paymentPortDefault: 3004