apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-teacher-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: micro-teacher
  template:
    metadata:
      labels:
        component: micro-teacher
    spec:
      containers:
        - name: micro-teacher
          image: mikedutuandu/micro_teacher
          ports:
            - containerPort: 3001
          env:
            - name: MICRO_LEARNER_HOST
              value: micro-learner-cluster-ip-service
            - name: MICRO_LEARNER_PORT
              value: '3002'
            - name: MICRO_BOOKING_HOST
              value: micro-booking-cluster-ip-service
            - name: MICRO_BOOKING_PORT
              value: '3003'
      imagePullSecrets:
        - name: regcred

