grpc:
  portDefault: 3003

sub:
  projectID: learn-drive-253814

repo:
  mongoConnectString: mongodb+srv://admin:110289@bookingcluster-tgpah.gcp.mongodb.net/test?retryWrites=true&w=majority
  mongoDBName: bookings

event:
  eventHostDefault: ""
  eventPortDefault: 3005
jwt:
  secretKey: mySuperSecretKeyLol
  tokenExpired: 72 #hour
  issuer: micro_booking #hour