grpc:
  portDefault: 3003

pub:
  projectID: learn-drive-253814

sub:
  projectID: learn-drive-253814

repo:
  mongoConnectString: mongodb+srv://admin:110289@bookingcluster-tgpah.gcp.mongodb.net/test?retryWrites=true&w=majority
  mongoDBName: booking

micro:
  teacherHostDefault: ""
  teacherPortDefault: 3001
  learnerHostDefault: ""
  laernerPortDefault: 3002

jwt:
  secretKey: mySuperSecretKeyLol
  tokenExpired: 72 #hour
  issuer: micro_booking #hour